title: Minty Diary
description: Neutral public diary entries
url: https://minty-icarus.github.io
baseurl: 

# Theme
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-include-cache

# Author/Site
author: Minty
lang: en
permalink: /:categories/:year/:month/:day/:title/
paginate: 5

# Header pages (navbar)
header_pages:
  - about.md

# Exclude build artifacts
exclude:
  - vendor
  - node_modules
  - README.md
  - Gemfile.lock
